import json
import os
import webbrowser
from datetime import date, datetime

class ChartEngine:
    def __init__(self, runtime):
        self.runtime = runtime
    
    def generate_chart(self, input_ref, chart_type, label_col, value_col, title, target):
        df = self.runtime.dataframes.get(input_ref)
        if not df:
            print(f"Error: Table '{input_ref}' not found")
            return
        
        labels = [str(row.get(label_col, "")) for row in df.rows]
        values = [self._to_number(row.get(value_col, 0)) for row in df.rows]
        
        colors = [
            "rgba(54, 162, 235, 0.8)",
            "rgba(255, 99, 132, 0.8)",
            "rgba(75, 192, 192, 0.8)",
            "rgba(255, 206, 86, 0.8)",
            "rgba(153, 102, 255, 0.8)",
            "rgba(255, 159, 64, 0.8)",
            "rgba(199, 199, 199, 0.8)",
        ]
        
        bg_colors = [colors[i % len(colors)] for i in range(len(labels))]
        
        html = f"""<!DOCTYPE html>
<html>
<head>
    <title>Dapine Chart - {title}</title>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <style>
        body {{
            font-family: 'Segoe UI', sans-serif;
            background: #1a1a2e;
            color: white;
            display: flex;
            justify-content: center;
            align-items: center;
            min-height: 100vh;
            margin: 0;
        }}
        .container {{
            background: #16213e;
            padding: 30px;
            border-radius: 15px;
            box-shadow: 0 10px 40px rgba(0,0,0,0.5);
            width: 80%;
            max-width: 900px;
        }}
        h1 {{
            text-align: center;
            color: #e94560;
            margin-bottom: 30px;
        }}
        canvas {{
            max-height: 500px;
        }}
        .footer {{
            text-align: center;
            margin-top: 20px;
            color: #888;
            font-size: 14px;
        }}
    </style>
</head>
<body>
    <div class="container">
        <h1>📊 {title}</h1>
        <canvas id="chart"></canvas>
        <div class="footer">Generated by Dapine 🚀</div>
    </div>
    <script>
        const ctx = document.getElementById('chart').getContext('2d');
        new Chart(ctx, {{
            type: '{chart_type}',
            data: {{
                labels: {json.dumps(labels)},
                datasets: [{{
                    label: '{value_col}',
                    data: {json.dumps(values)},
                    backgroundColor: {json.dumps(bg_colors)},
                    borderColor: {json.dumps(bg_colors)},
                    borderWidth: 2,
                    borderRadius: 5,
                    hoverBorderWidth: 3,
                }}]
            }},
            options: {{
                responsive: true,
                plugins: {{
                    legend: {{
                        labels: {{ color: 'white', font: {{ size: 14 }} }}
                    }}
                }},
                scales: {{
                    y: {{
                        beginAtZero: true,
                        ticks: {{ color: '#ccc' }},
                        grid: {{ color: '#333' }}
                    }},
                    x: {{
                        ticks: {{ color: '#ccc' }},
                        grid: {{ color: '#333' }}
                    }}
                }}
            }}
        }});
    </script>
</body>
</html>"""
        
        with open(target, "w", encoding="utf-8") as f:
            f.write(html)
        
        print(f"✅ Chart saved to {target}")
        webbrowser.open(f"file:///{os.path.abspath(target)}")
    
    def _to_number(self, val):
        if val is None:
            return 0
        try:
            return float(val)
        except (ValueError, TypeError):
            return 0