import json
import os
import webbrowser
from datetime import datetime

class ReportEngine:
    def __init__(self, runtime):
        self.runtime = runtime
    
    def generate_report(self, input_ref, title, target):
        df = self.runtime.dataframes.get(input_ref)
        if not df:
            print(f"Error: Table '{input_ref}' not found")
            return
        
        now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        
        md = f"""# {title}

**Generated:** {now}  
**Rows:** {len(df.rows)}  
**Columns:** {', '.join(df.schema)}

---

## Data Preview

"""
        # Table
        if df.rows:
            # Header
            md += "| " + " | ".join(df.schema) + " |\n"
            md += "| " + " | ".join(["---"] * len(df.schema)) + " |\n"
            
            # Rows (max 20)
            for row in df.rows[:20]:
                vals = [str(row.get(c, "")) for c in df.schema]
                md += "| " + " | ".join(vals) + " |\n"
            
            if len(df.rows) > 20:
                md += f"\n*Showing 20 of {len(df.rows)} rows*\n"
        
        # Stats section
        md += "\n---\n\n## Column Statistics\n\n"
        
        for col in df.schema:
            values = []
            for r in df.rows:
                v = r.get(col)
                if isinstance(v, (int, float)):
                    values.append(v)
            
            if values:
                import statistics
                md += f"### {col}\n"
                md += f"- **Min:** {min(values)}\n"
                md += f"- **Max:** {max(values)}\n"
                md += f"- **Mean:** {statistics.mean(values):.2f}\n"
                if len(values) > 1:
                    md += f"- **Median:** {statistics.median(values):.2f}\n"
                    md += f"- **Std Dev:** {statistics.stdev(values):.2f}\n"
                md += "\n"
        
        # Lineage section
        if self.runtime.lineage_log:
            md += "---\n\n## Data Lineage\n\n"
            for entry in self.runtime.lineage_log:
                md += f"- {entry}\n"
        
        md += "\n---\n\n*Report generated by Dapine*"
        
        with open(target, "w", encoding="utf-8") as f:
            f.write(md)
        
        print(f"✅ Report saved to {target}")
        #webbrowser.open(f"file:///{os.path.abspath(target)}")